### ISSUE TITLE
Issues adding group members in DSTS 

### ISSUE THREAD

**Issue by lindsaypoirier** [PECE-project/pece-distro#26]
I received an email that a user requested to join a group I own, "Slow Disaster" in the DSTS site. When I click through the link to approve the request, I receive an "Access Denied" message. I've made sure that I'm logged in and still own the account. On further inspection, it appears that none of my groups have the "group" tab at the top where I would typically go to add group members.

**Comment by revagomes** [comment]
@lindsaypoirier Please check your user's role on those groups to make sure that your user has one of the following roles: **administrator member** or **group administrator**. After the last PECE distro releases, group permissions have been updated due to security matters, so from now on only a "administrator member" is able to "_allow or deny another user's subscription requests_" and only a 'group administrator' is able to "_manage/change group's advanced settings (security implications)_" on groups.

I have sent an invitation for poiril user, adding **administrator member** and **group administrator** roles on **Slow Disaster** group.

Please let me know if you will be able to approve the request now.

**Comment by lindsaypoirier** [comment]
Hi Renato,

My apologies. I didn't set this up right. Alli Morgan submitted this request via an external survey form, and it created a ticket with my GitHub account. Can you look into this for user account alli.morgan?

Thank you!

**Comment by revagomes** [comment]
@lindsaypoirier, No problem.
I have updated alli.morgan's user account on "Slow Disaster" group to add "administrator member" role.
Please let me know if there is something else I can help on.
