### ISSUE TITLE
Error with latest PECE update

### ISSUE THREAD

**Issue by Honoluluskye** [PECE-project/pece-distro#58]
I just updated my instance to the latest and now getting this error when I try to open the site (www.researchdatashare.org).

![screen shot 2019-02-13 at 11 14 52 am](https://user-images.githubusercontent.com/6000846/52697414-78c5e580-2f82-11e9-8193-46592b6cd436.png)

**Comment by revagomes** [comment]
@Honoluluskye I've noticed that some files from Drupal core where missing on PECE v1.15 previously released due to .gitignore default settings.
I've already updated PECE v1.15 release to add that missing files. Please download the latest release (https://github.com/PECE-project/pece-distro/releases/tag/v1.15) and let me know if it's working as expected.
